import "./globals.css";
import Header from "./Component/Header";
import Footer from "./Component/Footer";

export const metadata = {
  title: "Taufik islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
